export const LanguageSkillsList ={ 
    EN:[
        {
            title:"Spanish",
            level:5
        },
        {
            title:"English",
            level:3
        },
        {
            title:"Italian",
            level:0
        }
    ],
    ES:[
        {
            title:"Español",
            level:5
        },
        {
            title:"Inglés",
            level:3
        },
        {
            title:"Italiano",
            level:0
        },
    ]}